# Generated by Django 5.2.8 on 2026-01-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auction_images/'),
        ),
    ]
