# Generated by Django 5.2.8 on 2026-01-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('automobile', 'Automobile'), ('real_estate', 'Real Estate'), ('art', 'Art & Collectibles'), ('others', 'Others')], max_length=50),
        ),
    ]
