# Generated by Django 5.2.8 on 2026-01-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bid_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
