# Generated by Django 5.2.8 on 2026-01-27 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionitem_is_approved_alter_auctionitem_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='reserve_price',
        ),
    ]
