# Generated by Django 5.2.8 on 2026-01-27 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_auctionitem_reserve_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='is_active',
        ),
    ]
