# Generated by Django 5.2.8 on 2026-01-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_auctionitem_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
