# Generated by Django 5.2.8 on 2026-01-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auctionitem_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
