# Generated by Django 5.2.8 on 2026-02-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctionitem_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='winner_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
